import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/Navigation/Header";
import { cn } from "@/lib/utils";

const redHatDisplay = Red_Hat_Display({
  weight: ["300", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(redHatDisplay.className,)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
